# conda env create --file environment.yml
# conda activate cbb_predict_default

name: tuyabot_llm
channels: 
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.3
  - transformers=4.49.0
  - accelerate=1.4.0
  - altair=5.5.0
  - beautifulsoup4=4.13.3
  - chromadb=0.6.3
  - dotenv=0.9.9
  - gradio=5.20.0
  - httptools=0.6.4
  - ipykernel=6.29.5
  - langchain=0.3.19
  - langchain-community=0.3.18
  - langchain-huggingface=0.1.2
  - langchain-openai=0.3.7
  - linkify-it-py=2.0.3
  - matplotlib=3.10.1
  - mdit-py-plugins=0.4.2
  - nltk=3.9.1
  - pip-chill=1.0.3
  - pycryptodome=3.21.0
  - pyprojroot=0.3.0
  - torchaudio=2.6.0
  - torchvision=0.21.0
  - watchfiles=1.0.4
  - pip:
      