# conda env create --file environment.yml
# conda activate cbb_predict_default

name: tuyabot_llm
channels: 
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pyprojroot=0.3.0
  - ipykernel=6.29.4
  - pytz=2024.1
  - pip-chill=1.0.3
  - pyodbc=5.1.0
  - python-dotenv=1.0.1
  - pandas=2.2.2
  - ydata-profiling=4.8.3
  - hydra-core=1.3.2
  - openpyxl=3.1.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - mlflow=2.11.3
  - sphinx=7.4.7
  - pydata-sphinx-theme=0.15.4
  - python=3.11.3
  - pip:
      